root: true
env:
  es2022: true
  node: true
extends:
  - xo
  - prettier
overrides:
  - extends:
      - xo-typescript
      - prettier
    files:
      - '*.ts'
      - '*.tsx'
    parserOptions:
      project:
        - 'tsconfig.json'
        - 'packages/*/tsconfig.json'
        - 'services/*/tsconfig.json'
    rules:
      '@typescript-eslint/array-type':
        - error
        - default: generic
      '@typescript-eslint/naming-convention':
        - error
        - selector: default
          format:
            - camelCase
          leadingUnderscore: allow
          trailingUnderscore: allow
        - selector: import
          format:
            - camelCase
            - PascalCase
        - selector: variable
          format:
            - camelCase
            - UPPER_CASE
          leadingUnderscore: allow
          trailingUnderscore: allow
        - selector: typeLike
          format:
            - PascalCase
        - selector: typeParameter
          format:
            - StrictPascalCase
          prefix:
            - T
parserOptions:
  ecmaVersion: latest
  sourceType: module
